import Link from "next/link";
import {notFound} from "next/navigation";
import {getProfile,viewer,feed,relationship,followList} from "@/lib/data";
import {Avatar} from "@/components/avatar";
import {Mutation} from "@/components/forms";
import {PostCard} from "@/components/post-card";
import {Empty} from "@/components/empty";
import {bn} from "@/lib/config";
export async function generateMetadata({params}:{params:Promise<{username:string}>}){const p=await getProfile((await params).username);return {title:p?.display_name??"প্রোফাইল পাওয়া যায়নি",description:p?.bio,robots:{index:!!p?.discoverable}};}
export default async function Page({params}:{params:Promise<{username:string}>}){const p=await getProfile((await params).username);if(!p)notFound();const [v,posts,following,followers,follows]=await Promise.all([viewer(),feed({author:p.id}),relationship(p.id),followList(p.id,"followers"),followList(p.id,"following")]);const mine=v?.id===p.id;return <><section className={`profile-card card accent-${p.accent}`}><div className="profile-cover"><span aria-hidden="true">{p.status||"✦"}</span></div><div className="profile-content"><div className="profile-top"><Avatar profile={p} large/>{mine?<Link className="button button-small" href="/settings/profile">নিজের মতো করি</Link>:v?<Mutation action="follow" values={{id:p.id,enabled:!following}} label={following?"সাথে আছি ✓":"সাথে থাকি +"} pressed={following}/>:<Link className="button button-small" href="/login">সাথে থাকি +</Link>}</div><h1>{p.display_name}</h1><p className="username">@{p.username}</p>{p.bio&&<p className="profile-bio">{p.bio}</p>}<div className="profile-facts">{p.education&&<span>🌱 {p.education}</span>}{p.institution&&<span>🏛️ {p.institution}</span>}{p.class_year&&<span>{p.class_year}</span>}{p.ssc_batch&&<span>SSC {p.ssc_batch}</span>}{p.hsc_batch&&<span>HSC {p.hsc_batch}</span>}</div><div className="tag-cloud">{p.hobbies.map(h=><Link className="chip" href={`/discover?q=${encodeURIComponent(h)}`} key={h}>{h}</Link>)}</div><div className="profile-links"><Link href={`/u/${p.username}/followers`}><b>{bn(followers.length)}</b> জন সাথে আছে</Link><Link href={`/u/${p.username}/following`}><b>{bn(follows.length)}</b> জনের সাথে আছি</Link></div>{v&&!mine&&<details className="safety-options"><summary>নিরাপত্তা ও অপশন</summary><div><Link href={`/report?type=user&id=${p.id}`}>রিপোর্ট করি</Link><Mutation action="mute" values={{id:p.id,enabled:true}} label="চুপ রাখি (mute)"/><Mutation action="block" values={{id:p.id,enabled:true}} label="ব্লক করি" confirm="একে অন্যের পোস্ট আর দেখতে পাবে না। ব্লক করবে?"/></div></details>}</div></section><h2 className="section-heading">{mine?"আমার":"এই আড্ডাবাজের"} ছোট্ট কথাগুলো</h2><div className="post-list">{posts.map(post=><PostCard key={post.id} post={post} viewer={v}/>)}{!posts.length&&<Empty text="এখনো কোনো কথা বলা হয়নি।"/>}</div></>;}
